object Versions {
    const val gradle = "8.1.4"
    const val kotlin = "1.9.0"
    const val kapt = "1.6.20"
    const val navigationPlugin = "2.6.0"

    const val sdp = "1.0.6"
    const val ssp = "1.0.6"
    const val glide = "4.12.0"
    const val hiltDI = "2.49"
    const val okhttp3 = "4.11.0"
    const val hiltWork = "1.1.0"
    const val workManager = "2.8.1"
    const val startupRuntime = "1.1.1"
    const val retrofit = "2.9.0"
    const val coreKtx = "1.12.0"
    const val appcompat = "1.6.1"
    const val navigation = "2.7.5"
    const val fragmentKtx = "1.6.2"
    const val materialUi = "1.10.0"
    const val activityKtx = "1.8.1"
    const val gmsPlayService  ="19.0.1"
    const val preferenceKtx = "1.2.0"
    const val coroutinesCore = "1.7.3"
    const val constraintLayout = "2.1.4"
    const val concurrentFutures = "1.1.0"
    const val lifecycleExtensions = "2.2.0"
    const val lifecycleRuntimeKtx = "2.6.2"
    const val lifecycleLivedataKtx = "2.6.2"
    const val lifecycleViewmodelKtx = "2.6.2"

    const val junit = "4.13.2"
    const val extJunit = "1.1.5"
    const val espresso = "3.5.1"
}